### ISSUE TITLE
Figure out how to introspect a .jl file to get its types, their fields, and how these types relate to each other (e.g., via inheritance)

### ISSUE THREAD

**Issue by elimisteve** [KwatMDPhD/Immunology.jl#1]

**Comment by elimisteve** [comment]
From https://docs.julialang.org/en/v1/devdocs/reflection/ --

Get everything exported from a module `m` by running `names(m)` --

> The exported names for a Module are available using names(m::Module), which will return an array of Symbol elements representing the exported bindings. names(m::Module, all = true) returns symbols for all bindings in m, regardless of export status.

---

Get the field names of a type:

```julia
julia> struct Point
           x::Int
           y
       end

julia> fieldnames(Point)
(:x, :y)
```

---

Get a list of all types that a given type inherited from (I think?):

> The direct subtypes of any DataType may be listed using subtypes. For example, the abstract DataType AbstractFloat has four (concrete) subtypes:

```julia
julia> subtypes(AbstractFloat)
4-element Vector{Any}:
 BigFloat
 Float16
 Float32
 Float64
```

---

Putting it all together:

Each type could follow a certain naming convention to help distinguish them from functions and methods, like by starting with a capital letter (as is done already). Then you could get an array of all the types in a module by doing something like

```julia
type_names = filter(name -> string(name)[1] in 'A':'Z', names(Immunology))
all_types = [eval(typ) for typ = exported_type_names]

all_types_subtypes = [subtypes(typ) for typ = all_types]
all_types_fieldnames = [fieldnames(typ) for typ = all_types]
```

Should be pretty simple to loop through the names and draw lines between them! @KwatMDPhD

**Comment by KwatMDPhD** [comment]
Worked!
